config/routes.rb
Runtracker::Application.routes.draw do
  resources :routes  
  resources :runners do
      resources :results
      resources :favorites  
  end 
  resources :sessions 
  resources :roles
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "runners#new", :as => "sign_up"
  root :to => "routes#index"     

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base            
  belongs_to :runner
  
  validates_uniqueness_of :route_id, :scope => [:route_id,:runner_id] , :message => "must be unique"
end

app/models/result.rb
class Result < ActiveRecord::Base    
  belongs_to :runner
end

app/models/role.rb
class Role < ActiveRecord::Base 

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :runner
  
  validates_presence_of :name, :on => :create, :message => "can't be blank"  
end

app/models/runner.rb
require 'bcrypt'   
class Runner < ActiveRecord::Base      
  belongs_to :role    
  has_many :results
  has_many :favorites
  has_many :routes
  
  validates_presence_of :name, :on => :create   
  attr_accessible :email, :password, :password_confirmation, :name
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create  
  validates_presence_of :email
  validates_uniqueness_of :email    
  
  def self.authenticate(email, password)      
    runner = find_by_email(email)
    if runner && runner.password_hash == BCrypt::Engine.hash_secret(password, runner.password_salt)
      runner
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery
  helper_method :current_user   
   
  private
  
  def current_user
    @current_user ||= Runner.find(session[:runner_id]) if session[:runner_id]
  end   
  
  def check_role(role_name) 
    begin
      if current_user.role.name == role_name.to_s
        return true
      else
        redirect_to runner_path(current_user) 
      end    
    rescue  
      redirect_to runner_path(current_user) 
    end
  end           
       
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def new       
    @favorite = current_user.favorites.new     
    @favorite.runner_id = @current_user.id
    @favorite.route_id = params[:route_id]
    
    if @favorite.save  
      redirect_to runner_path(@current_user.id), :notice => "Favorite was successfully added."
    else
      redirect_to runner_path(@current_user.id), :notice => "Favorite could not be added." 
    end   
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to(favorites_url)
  end
end

app/controllers/restricted_controller.rb
class RestrictedController < ApplicationController    
  before_filter :authenticate
  private   
  def authenticate
    if current_user.blank?
      redirect_to new_session_path
    end  
  end
end         

app/controllers/results_controller.rb
class ResultsController < ApplicationController         
            
  before_filter :find_runner
  def index
    @results = @runner.results
  end

  def show
    @result = @runner.results.find(params[:id])
  end

  def new   
    @result = Result.new    
    @result.route_id = params[:route_id]
    @effort = []
    20.downto(0) {|i| @effort<< i*5 }         
  end

  def edit
    @result = @runner.results.find(params[:id]) 
    @effort = []
    20.downto(0) {|i| @effort<< i*5 }       
  end

  def create
    @result = current_user.results.new(params[:result])
    if @result.save
      redirect_to(runner_results_path, :notice => 'Result was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @result = Result.find(params[:id])
    if @result.update_attributes(params[:result])
      redirect_to(@result, :notice => 'Result was successfully updated.')
    else
      render :action => "edit"
    end  
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy  
    redirect_to(runner_results_path(@runner), :notice => 'Result was successfully removed.')
  end 
  
  def find_runner
    @runner = Runner.find(current_user)
  end              
  
end

app/controllers/roles_controller.rb
class RolesController < RestrictedController    
  
  def index 
    check_role('Admin') 
    @runners = Runner.all   
  end
                             
end      

app/controllers/routes_controller.rb
class RoutesController < RestrictedController
  def index
    @routes = Route.all    
  end

  def show
    @route = Route.find(params[:id])
  end

  def new
    @route = Route.new
  end

  def edit
    @route = Route.find(params[:id])
  end

  def create
    @route = Route.new(params[:route])     
    @route.runner_id = current_user
    
    if @route.save
      redirect_to(@route, :notice => 'Route was successfully created.')  
    else
      render :action => "new"
    end
  end

  def update
    @route = Route.find(params[:id])
    
    if @route.update_attributes(params[:route])
       redirect_to(@route, :notice => 'Route was successfully updated.')
    else
       render :action => "edit"
    end
  end

  def destroy
    @route = Route.find(params[:id])
    @route.destroy
  end
end

app/controllers/runners_controller.rb
class RunnersController < RestrictedController     
  
  def index
    @runners = Runner.all
  end
  
  def new
    @runner = Runner.new
  end   
  
  def show 
    @runner = current_user
    @favorites = current_user.favorites 
    @routes = current_user.routes
    @results = current_user.results
  end
  
  def create
    @runner = Runner.new(params[:runner]) 
    @runner.role_id = 2
    if @runner.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController    

  def new
  end
  
  def create
    runner = Runner.authenticate(params[:email], params[:password])
    if runner
      session[:runner_id] = runner.id
      redirect_to runner_path(runner.id), :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:runner_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end     
 
end 

app/helpers/application_helper.rb
module ApplicationHelper         

  def find_user(id)       
    if !id.blank?
      runner = Runner.find_by_id(id)
      if runner.blank?
        return ''
      else
        return runner.name
      end
    else
      return ''
    end
  end   
  
    def check_role(role_name) 
    begin
      if current_user.role.name == role_name.to_s
        return true
      else
        return false
      end    
    rescue  
      return false
    end
  end             
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :runner_id %><br />
    <%= f.text_field :runner_id %>
  </div>
  <div class="field">
    <%= f.label :route_id %><br />
    <%= f.text_field :route_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <tr>
    <th>Runner</th>
    <th>Route</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.runner_id %></td>
    <td><%= favorite.route_id %></td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Favorite', new_runner_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Runner:</b>
  <%= @favorite.runner_id %>
</p>

<p>
  <b>Route:</b>
  <%= @favorite.route_id %>
</p>


<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/_user_bar.html.erb
<div class="userdetails">
  <div id="user-bar-greeting">
 <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>                 
  </div>  
  <div id="user-bar-action"></div>
</div>          

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
  <head> 
    <title>
      Just Run
    </title> 
<%= javascript_include_tag :all %>       
<script type="text/javascript">
  $.noConflict();
  // Code that uses other library's $ can follow here.
</script>
    <link href='/stylesheets/reset-fonts.css' media='screen' rel='stylesheet' type='text/css' />  
    <link href='/stylesheets/tables.css' media='screen' rel='stylesheet' type='text/css' />  
    <link href='/stylesheets/text.css' media='screen' rel='stylesheet' type='text/css' />
    <link href='/stylesheets/960.css' media='screen' rel='stylesheet' type='text/css' />
    <link href='/stylesheets/layout.css' media='screen' rel='stylesheet' type='text/css' />
    <link href='/stylesheets/icis.css' media='screen' rel='stylesheet' type='text/css' />
    <link href='/stylesheets/admin.css' media='screen' rel='stylesheet' type='text/css' />
    <link href='/stylesheets/dropdownmenu.css' media='screen' rel='stylesheet' type='text/css' />  
    <link href='/stylesheets/autocomplete.css' media='screen' rel='stylesheet' type='text/css' />      
    <%= csrf_meta_tag %>
  </head>
<body>
  <div class='container_12'>

    <div class='grid_12 header'>
      <%= render :partial => 'layouts/user_bar' %>
      <h1 id='branding'>
        Run Tracker
      </h1>
      <%= render :partial => '/menus/main' %>
    </div>
    <div class='clear'></div>
    <div class='grid_12'>
      <% if flash[:notice] %><div id="notice" class="flashBox"><%= flash[:notice] %></div><% end %>   
      <% if flash[:warning] %><div id="notice" class="flashBox"><%= flash[:warning] %></div><% end %>   
      <%= yield %>
    </div>

    <div class='clear'></div>
    <div class='grid_12' id='site_info'>

      <p class='box'>
        &copy; Run Tracker
      </p>
    </div>
    <div class='clear'></div>
  </div>
</body> 
</html> 

app/views/menus/_main.html.erb
<div id="smoothmenu" class="ddsmoothmenu">
	<ul>    
	  <li><%= link_to "Profile", runner_path(current_user) unless current_user.blank? %></li>  
	  <li><%= link_to "Routes", routes_path %></li>  
	  <li><%= link_to "Runners", runners_path %></li>  
	  <% if check_role('Admin') %> 
	    <li><%= link_to "Roles", roles_path %></li> 
	  <% end %>
	</ul>   
		<br style="clear: left" />    
</div>

app/views/results/_form.html.erb
<style>
	#demo-frame > div.demo { padding: 10px !important; };
</style>  
	
	<script type="text/javascript">
  var j = jQuery.noConflict();
    // Code that uses jQuery's $ can follow here. 
    j(function() {
		j( "#slider" ).slider({
			value:1,
			min: 1,
			max: 5,
			step: 1,
			slide: function( event, ui ) {
        var val = ui.value;  
			  switch (val)
        {
          case 1:
            result = "Great"
            break
          case 2:
            result = "Good" 
            break
          case 3:
            result = "O.K" 
            break
          case 4:
            result = "Bad" 
            break
          case 5:
            result = "Worse" 
            break
        }    
        j( "#amount" ).val( result );                  
				document.getElementById ("result_feelings").value = ui.value
			}
		});  
		document.getElementById ("result_feelings").value = j( "#slider" ).slider( "value" );
		j( "#amount" ).val( "Great" );   
	});               
  
  // Code that uses other library's $ can follow here.
</script>

<%= form_for([current_user,@result]) do |f| %>  
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :route_id %><br />
    <%= f.text_field :route_id %>
  </div>
  <div class="field">
    <%= f.label :custom_distance %><br />
    <%= f.text_field :custom_distance %>
  </div>
  <div class="field">
    <%= f.label :time_minutes %><br />
    <%= f.text_field :time_minutes %>
  </div>
  <div class="dateselect">
    <%= f.label :date_of_run %><br />
    <%= f.date_select :date_of_run, {},html_options = {:class => "dateselect"} %> 
  </div>
  <div class="field">
    <%= f.label :effort %><br />
    <%= f.select :effort, @effort %>   
  </div>   
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time,{},html_options = {:class => "dateselect"} %>  
  </div>  
  <div class="field">
    <%= f.label :weather %><br />
    <%= f.text_field :weather %>
  </div>  
    <div class="field">
    <%= f.label :feelings %><br />
    <%= f.text_field :feelings, :type => 'hidden' %> 
    <p>
	    <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;" />
    </p>
    <div id="slider" style="width:100px; margin:10px;"></div> 
  </div>  
 
  <div class="field"> 
    <%= f.label :exercise_id %><br />
    <%= f.text_field :exercise_id %>
  </div>
            
  <div class="actions">
    <%= f.submit 'Save', :class=>'savelink' %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', runner_result_path(@runner,@result) %> |
<%= link_to 'Back', runner_results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Runner</th>
    <th>Route</th>
    <th>Custom distance</th>
    <th>Time minutes</th>
    <th>Date of run</th>
    <th>Effort</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.runner_id %></td>
    <td><%= result.route_id %></td>
    <td><%= result.custom_distance %></td>
    <td><%= result.time_minutes %></td>
    <td><%= result.date_of_run %></td>
    <td><%= result.effort %></td>
    <td><%= link_to 'Show', runner_result_path(@runner,result) %></td>
    <td><%= link_to 'Edit', edit_runner_result_path(@runner,result) %></td>
    <td class="delete"><%= link_to 'Destroy', runner_result_path(@runner,result), :confirm => 'Are you sure?', :method => :delete %></td>     
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_runner_result_path %>

app/views/results/new.html.erb
<h1>Log a Run</h1>

<%= render 'form' %>
<p>
  <%= link_to 'Back to Profile', runner_path(@current_user), :class => 'backlink'%>
</p>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Runner:</b>
  <%= @result.runner_id %>
</p>

<p>
  <b>Route:</b>
  <%= @result.route_id %>
</p>

<p>
  <b>Custom distance:</b>
  <%= @result.custom_distance %>
</p>

<p>
  <b>Time minutes:</b>
  <%= @result.time_minutes %>
</p>

<p>
  <b>Date of run:</b>
  <%= @result.date_of_run %>
</p>

<p>
  <b>Effort:</b>
  <%= @result.effort %>
</p>


<%= link_to 'Edit', edit_runner_result_path(@runner,@result) %> |
<%= link_to 'Back', runner_results_path %>

app/views/roles/index.html.erb
<h1>Listing Runner / Role</h1>   
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
  </tr>
<% @runners.each do |runner| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= runner.name %></td>
    <td><%= runner.email %></td>  
    <td><%= runner.role.name unless runner.role.blank? %></td>  
  </tr>
<% end %>
</table>     

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit :class => "savelink" %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Edit Route</h1>
<p><%= link_to 'Back', routes_path, :class => 'backlink'  %></p>     
<%= render 'form' %>

app/views/routes/index.html.erb
<h1>Listing Routes</h1>
<p><%= link_to 'New Route', new_route_path, :class => "addlink" %></p>    
<table>
  <tr>
    <th>Name</th>    
    <th>Creator</th>
    <th>Location</th>
    <th>Url</th>
    <th>Distance (m)</th>
    <th></th> 
 
      <th></th>
      <th></th>

  </tr>

<% @routes.each do |route| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= route.name.to_s %></td>
    <td><%= find_user(route.runner_id) %></td>
    <td><%= route.location %></td>
    <td><%= route.url %></td>
    <td><%= route.distance %></td>
    <td class="view"><%= link_to 'Show', route %></td>  
    <% if check_role('Admin') %>  
      <td class="edit"><%= link_to 'Edit', edit_route_path(route) %></td>
      <td class="delete"><%= link_to 'Destroy', route, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<h1>Showing Route</h1>
<p>
  <b>Name:</b>
  <%= @route.name %>
</p>

<p>
  <b>Location:</b>
  <%= @route.location %>
</p>

<p>
  <b>Url:</b>
  <%= @route.url %>
</p>

<p>
  <b>Distance:</b>
  <%= @route.distance %>
</p>

<p>
  <b>Description:</b>
  <%= @route.description %>
</p>
<p>
  <%= link_to 'Back', routes_path, :class => "backlink" %>  
</p>

app/views/runners/_favorites.html.erb
<h4>Favorite Routes</h4>
<table>
  <tr>
    <th>Route</th>
    <th>Add Result</th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= favorite.route_id %></td>
    <td class="add"><%= link_to 'Log a Run', new_runner_result_path(@runner,:route_id =>favorite.route_id ) %></td>
  </tr>
<% end %>
</table>      

app/views/runners/_myroutes.html.erb
<h4>My Routes</h4>
<p><%= link_to 'New Route', new_route_path, :class => "addlink" %></p>    
<table>
  <tr>
    <th>Name</th>    
    <th>Location</th>
    <th>Url</th>
    <th>Distance (m)</th>  
    <th>Add Result</th>
    <th>View</th>
    <% if check_role('Admin') %> 
      <th></th>
      <th></th>
    <% end %>
  </tr>

<% @routes.each do |route| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= route.name.to_s %></td>
    <td><%= route.location %></td>
    <td><%= link_to 'View Route', route.url %></td>
    <td><%= route.distance %></td>   
    <td class="add"><%= link_to 'Log a Run', new_runner_result_path(@runner,:route_id =>route.id ) %></td> 
    <td class="view"><%= link_to 'Show', route %></td>  
    <% if check_role('Admin') %>  
      <td class="edit"><%= link_to 'Edit', edit_route_path(route) %></td>
      <td class="delete"><%= link_to 'Destroy', route, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/runners/_results.html.erb
<h4>Recent Results</h4>  
<p>
  <%= link_to 'Log a Run', new_runner_result_path(@runner), :class => 'addlink' %>     
</p>      

<table>
  <tr>
    <th>Distance</th>
    <th>Time</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= result.custom_distance %></td>
    <td><%= result.time_minutes %></td>
    <td><%= result.date_of_run %></td>
    <td class="view"><%= link_to 'Show', runner_result_path(@runner,result) %></td>
    <td class="edit"><%= link_to 'Edit', edit_runner_result_path(@runner,result) %></td>
    <td class="delete"><%= link_to 'Destroy', runner_result_path(@runner,result), :confirm => 'Are you sure?', :method => :delete %></td>     
  </tr>
<% end %>
</table>                              

app/views/runners/index.html.erb
<h1>Listing Runners</h1>   
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
<% @runners.each do |runner| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td><%= runner.name %></td>
    <td><%= runner.email %></td>
  </tr>
<% end %>
</table>

app/views/runners/new.html.erb
<h1>Sign Up</h1>

<%= form_for @runner do |f| %>
  <% if @runner.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @runner.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>   
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p> 
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit 'SignUp', :class => 'savelink' %></p>
<% end %>

app/views/runners/show.html.erb
<h1>Profile</h1>   
     
<div class="grid_6 alpha">
  <%= render :partial => 'favorites' %>  
</div>        
<div class="grid_6 omega">
  <%= render :partial => 'results' %>  
</div>   
<div class="clear"></div>
<%= render :partial => 'myroutes' %>  

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>